# SPDX-FileCopyrightText: 2023-2026 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 sudo-Tiz
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Flaresolverr paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ flaresolverr_uid }}"
    group: "{{ flaresolverr_gid }}"
  with_items:
    - "{{ flaresolverr_base_path }}"

- name: Ensure Flaresolverr support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ flaresolverr_base_path }}/{{ item }}"
    owner: "{{ flaresolverr_uid }}"
    group: "{{ flaresolverr_gid }}"
    mode: "0640"
  with_items:
    - env
    - labels
  register: flaresolverr_support_files_result

- name: Ensure Flaresolverr container image is pulled via community.docker.docker_image_pull
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image_pull:
    name: "{{ flaresolverr_container_image }}"
    pull: always
  register: flaresolverr_container_image_pull_result_ansible_module
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: flaresolverr_container_image_pull_result_ansible_module is not failed

- name: Ensure Flaresolverr container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ flaresolverr_container_image }}"
  register: flaresolverr_container_image_pull_result_command
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: flaresolverr_container_image_pull_result_command is not failed
  changed_when: "'Downloaded newer image' in flaresolverr_container_image_pull_result_command.stdout"

- name: Ensure Flaresolverr container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ flaresolverr_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: flaresolverr_network_creation_result

- name: Ensure Flaresolverr container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ flaresolverr_container_network }}
  register: flaresolverr_network_creation_result
  changed_when: flaresolverr_network_creation_result.rc == 0
  failed_when: flaresolverr_network_creation_result.rc != 0 and 'already exists' not in flaresolverr_network_creation_result.stderr

- name: Ensure Flaresolverr systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/flaresolverr.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ flaresolverr_identifier }}.service"
    mode: "0644"
  register: flaresolverr_systemd_service_result

- name: Determine whether Flaresolverr needs a restart
  ansible.builtin.set_fact:
    flaresolverr_restart_necessary: >-
      {{
        flaresolverr_support_files_result.changed | default(false)
        or flaresolverr_systemd_service_result.changed | default(false)
        or flaresolverr_container_image_pull_result_ansible_module.changed | default(false)
        or flaresolverr_container_image_pull_result_command.changed | default(false)
      }}
