# SPDX-FileCopyrightText: 2025 sudo-Tiz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of FlareSolverr systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ flaresolverr_identifier }}.service"
  register: flaresolverr_service_stat

- name: Uninstall FlareSolverr systemd services and files
  when: flaresolverr_service_stat.stat.exists | bool
  block:
    - name: Ensure FlareSolverr systemd service is stopped
      ansible.builtin.service:
        name: "{{ flaresolverr_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure FlareSolverr systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ flaresolverr_identifier }}.service"
        state: absent

    - name: Ensure FlareSolverr path doesn't exist
      ansible.builtin.file:
        path: "{{ flaresolverr_base_path }}"
        state: absent
